### PR TITLE
explicitly set port 9001 in all clsp urls

### PR DESCRIPTION
**Pull request by brainthinks**

### CODE REVIEW

**Review by dkemens — APPROVED** [review]

**Review by jsneko — COMMENTED** [review]
See nothing wrong with the implementation; however, should we have something in the README indicating the addition to the API?

**Comment by brainthinks** [comment]
would putting it in the changelog be sufficient?

**Comment by jsneko** [comment]
If you feel that's alright for anyone using the player / plugin I have no issue.

**Comment by dkemens** [comment]
My power is out, and I'm on 3g - so I'm very limited. Does it make sense to
make the port/address in a constant so it can be updated more easily in the
future?

**Pull request merged**
